### ISSUE TITLE
Outdated GitHub repo URL

### ISSUE THREAD

**Issue by joaopalmeiro** [will-stone/prettier-config#1]
Hi! 👋 

I was checking out several Prettier configuration packages and noticed that the [URL](https://github.com/will-stone/prettier-config/blob/main/package.json#L6) for the GitHub repository is out of date in the `package.json` file.

**Comment by will-stone** [comment]
Oh! Thanks ☺️ I’ll update that. This was originally part of a mono-repo with my ESLint config but I went off the structure so here we are. 

Anything interesting you’ve found on your Prettier config travels?

**Comment by joaopalmeiro** [comment]
I was mainly reviewing the resources I have in [this repository](https://gitlab.com/joaommpalmeiro/awesome-prettier) and seeing if I could find new things, at least for me (open issues). For example, I found an example of a Prettier config packaged with a plugin that is defined as peer dependency and that Astro has a plugin.

I hope the resources can be useful to you too!
